#!/bin/bash

mkdir /mnt/home
mkdir /mnt/data

chmod -R 777 /mnt/home
chmod -R 777 /mnt/data
chmod -R 777 /mnt/logs

cd /mnt/home

git clone https://github.com/alexmlamb/Timeseries.git

python Timeseries/lib/download_data.py

git clone https://github.com/alexmlamb/gpu_environment_setup.git

#0.7.0 is latest version confirmed to work.  
pip install --upgrade --no-deps theano

pip install -U boto

cp gpu_environment_setup/vimrc ~/.vimrc

cp gpu_environment_setup/theanorc ~/.theanorc
